[tool.poetry]
name = "solves"
version = "0.1.0"
description = ""
authors = ["Nikita <nvk.mpei@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mypy = "^1.11.2"
black = "^24.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
